"""geofence exit monitoring

Revision ID: 05be3125feff
Revises: 9797b18e9498
Create Date: 2026-08-05 17:39:31.418067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05be3125feff'
down_revision: Union[str, None] = '9797b18e9498'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('geofence_events',
    sa.Column('employee_id', sa.Uuid(), nullable=False),
    sa.Column('attendance_id', sa.Uuid(), nullable=False),
    sa.Column('geofence_id', sa.Uuid(), nullable=True),
    sa.Column('event_type', sa.Enum('ENTER', 'EXIT', 'RETURN', name='geofenceeventtype'), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['attendance_id'], ['attendance_records.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['geofence_id'], ['geofences.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('attendance_records', sa.Column('last_ping_seq', sa.Integer(), nullable=True))
    op.add_column('attendance_records', sa.Column('last_ping_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column(
        'attendance_records',
        sa.Column('outside_streak', sa.Integer(), nullable=False, server_default='0'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attendance_records', 'outside_streak')
    op.drop_column('attendance_records', 'last_ping_at')
    op.drop_column('attendance_records', 'last_ping_seq')
    op.drop_table('geofence_events')
    # ### end Alembic commands ###
