"""attendance_sessions_multi_per_day

Revision ID: 4cb7cdbeb134
Revises: c127266e3d3e
Create Date: 2026-08-06 12:56:44.820177

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4cb7cdbeb134'
down_revision: Union[str, None] = 'c127266e3d3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_attendance_employee_date', 'attendance_records', type_='unique')
    op.create_index('uq_attendance_one_open_session', 'attendance_records', ['employee_id'], unique=True, postgresql_where=sa.text('check_out_at IS NULL'), sqlite_where=sa.text('check_out_at IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_attendance_one_open_session', table_name='attendance_records', postgresql_where=sa.text('check_out_at IS NULL'), sqlite_where=sa.text('check_out_at IS NULL'))
    op.create_unique_constraint('uq_attendance_employee_date', 'attendance_records', ['employee_id', 'attendance_date'])
    # ### end Alembic commands ###
