"""face_recognition

Revision ID: 75b40a0c4e5e
Revises: d8b1f4a92c6e
Create Date: 2026-08-07 11:05:40.576643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75b40a0c4e5e'
down_revision: Union[str, None] = 'd8b1f4a92c6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('face_profiles',
    sa.Column('employee_id', sa.Uuid(), nullable=False),
    sa.Column('embedding', sa.JSON(), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('embedding_dimension', sa.Integer(), nullable=False),
    sa.Column('enrollment_photo_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id')
    )
    op.create_table('face_verification_attempts',
    sa.Column('employee_id', sa.Uuid(), nullable=False),
    sa.Column('similarity_score', sa.Float(), nullable=True),
    sa.Column('liveness_score', sa.Float(), nullable=True),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('failure_reason', sa.Enum('NO_FACE', 'MULTIPLE_FACES', 'INVALID_IMAGE', 'NOT_ENROLLED', 'LOW_SIMILARITY', 'LIVENESS_FAILED', 'MODEL_UNAVAILABLE', name='faceverificationfailurereason'), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_face_verification_attempts_employee_created', 'face_verification_attempts', ['employee_id', 'created_at'], unique=False)
    # NOTE: autogenerate also proposed dropping 'ix_employee_geofences_geofence_id'
    # here — pre-existing drift between the Geofence v2 model and the live DB,
    # unrelated to this module. Left alone; not this migration's blast radius.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_face_verification_attempts_employee_created', table_name='face_verification_attempts')
    op.drop_table('face_verification_attempts')
    op.drop_table('face_profiles')
    # ### end Alembic commands ###
