"""attendance and geofencing

Revision ID: 9797b18e9498
Revises: c88c555f8791
Create Date: 2026-08-05 13:34:06.223682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9797b18e9498'
down_revision: Union[str, None] = 'c88c555f8791'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('geofences',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('department_id', sa.Uuid(), nullable=True),
    sa.Column('center_latitude', sa.Float(), nullable=False),
    sa.Column('center_longitude', sa.Float(), nullable=False),
    sa.Column('radius_meters', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attendance_records',
    sa.Column('employee_id', sa.Uuid(), nullable=False),
    sa.Column('attendance_date', sa.Date(), nullable=False),
    sa.Column('check_in_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('check_in_latitude', sa.Float(), nullable=True),
    sa.Column('check_in_longitude', sa.Float(), nullable=True),
    sa.Column('check_in_accuracy_meters', sa.Float(), nullable=True),
    sa.Column('check_in_geofence_id', sa.Uuid(), nullable=True),
    sa.Column('check_out_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('check_out_latitude', sa.Float(), nullable=True),
    sa.Column('check_out_longitude', sa.Float(), nullable=True),
    sa.Column('check_out_accuracy_meters', sa.Float(), nullable=True),
    sa.Column('check_out_geofence_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('PRESENT', 'LATE', 'REMOTE', name='attendancestatus'), nullable=False),
    sa.Column('is_manual_entry', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.String(length=1000), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['check_in_geofence_id'], ['geofences.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['check_out_geofence_id'], ['geofences.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'attendance_date', name='uq_attendance_employee_date')
    )
    op.create_index('ix_attendance_employee_checkin', 'attendance_records', ['employee_id', 'check_in_at'], unique=False)
    op.create_table('break_periods',
    sa.Column('attendance_id', sa.Uuid(), nullable=False),
    sa.Column('break_start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('break_end_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['attendance_id'], ['attendance_records.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_break_periods_attendance_id', 'break_periods', ['attendance_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_break_periods_attendance_id', table_name='break_periods')
    op.drop_table('break_periods')
    op.drop_index('ix_attendance_employee_checkin', table_name='attendance_records')
    op.drop_table('attendance_records')
    op.drop_table('geofences')
    # ### end Alembic commands ###
