"""break_period_location

Revision ID: c127266e3d3e
Revises: 05be3125feff
Create Date: 2026-08-06 12:43:40.617166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c127266e3d3e'
down_revision: Union[str, None] = '05be3125feff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('break_periods', sa.Column('start_latitude', sa.Float(), nullable=True))
    op.add_column('break_periods', sa.Column('start_longitude', sa.Float(), nullable=True))
    op.add_column('break_periods', sa.Column('start_accuracy_meters', sa.Float(), nullable=True))
    op.add_column('break_periods', sa.Column('start_geofence_id', sa.Uuid(), nullable=True))
    op.add_column('break_periods', sa.Column('end_latitude', sa.Float(), nullable=True))
    op.add_column('break_periods', sa.Column('end_longitude', sa.Float(), nullable=True))
    op.add_column('break_periods', sa.Column('end_accuracy_meters', sa.Float(), nullable=True))
    op.add_column('break_periods', sa.Column('end_geofence_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'break_periods', 'geofences', ['start_geofence_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'break_periods', 'geofences', ['end_geofence_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'break_periods', type_='foreignkey')
    op.drop_constraint(None, 'break_periods', type_='foreignkey')
    op.drop_column('break_periods', 'end_geofence_id')
    op.drop_column('break_periods', 'end_accuracy_meters')
    op.drop_column('break_periods', 'end_longitude')
    op.drop_column('break_periods', 'end_latitude')
    op.drop_column('break_periods', 'start_geofence_id')
    op.drop_column('break_periods', 'start_accuracy_meters')
    op.drop_column('break_periods', 'start_longitude')
    op.drop_column('break_periods', 'start_latitude')
    # ### end Alembic commands ###
