"""problem_reports

Revision ID: fec40df529fb
Revises: 359b6552fcad
Create Date: 2026-08-12 17:35:24.646251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fec40df529fb'
down_revision: Union[str, None] = '359b6552fcad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('problem_reports',
    sa.Column('employee_id', sa.Uuid(), nullable=False),
    sa.Column('attendance_id', sa.Uuid(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'RESOLVED', name='problemreportstatus'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['attendance_id'], ['attendance_records.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resolved_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_problem_reports_status_created', 'problem_reports', ['status', 'created_at'], unique=False)
    # NOTE: autogenerate also proposed dropping 'ix_employee_geofences_geofence_id'
    # here — same pre-existing drift already noted in 75b40a0c4e5e_face_recognition.py,
    # unrelated to this module. Left alone; not this migration's blast radius.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_problem_reports_status_created', table_name='problem_reports')
    op.drop_table('problem_reports')
    # ### end Alembic commands ###
